# Generated by Django 4.0.6 on 2022-09-30 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_active',
            new_name='terms',
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='test_user', max_length=255),
            preserve_default=False,
        ),
    ]
