from typing import Dict

pixel_data: Dict = {
    'error': False,
    'current_page': 1,
    'next_page': 2,
    'results': [
        {
            'asin': 'B09JJ1NKDK',
            'title': 'Google Pixel 4 (128GB, 6GB) 5.7", IP68 Water Resistant, Snapdragon 855, GSM/CDMA Factory Unlocked (AT&T/T-Mobile/Verizon/Fi) w/Fast Qi Wireless Pad (Clearly White)',
            'image': 'https://m.media-amazon.com/images/I/517rGuQMegL._AC_UY218_.jpg',
            'full_link': 'https://www.amazon.com/dp/B09JJ1NKDK/?psc=1',
            'prices': {
                'current_price': 459.99,
                'previous_price': -1.0,
                'currency': '$'
            },
            'reviews': {
                'total_reviews': 34,
                'stars': 3.8
            },
            'prime': False,
            'sponsored': True
        },
        {
            'asin': 'B08C4BXY41',
            'title': "Mobile Pixels Trio Max Portable Monitor, 14'' Full HD IPS Dual Triple Monitor for laptops, USB C/USB A Portable Screen,Windows/Mac/OS/Android/Switch Compatible (1x Monitor Only)",
            'image': 'https://m.media-amazon.com/images/I/81uySvxGB4L._AC_UY218_.jpg',
            'full_link': 'https://www.amazon.com/dp/B08C4BXY41/?psc=1',
            'prices': {
                'current_price': 309.0,
                'previous_price': 329.0,
                'currency': '$'
            },
            'reviews': {
                'total_reviews': 997,
                'stars': 4.1
            },
            'prime': False,
            'sponsored': True
        },
        {
            'asin': 'B095PY85HG',
            'title': 'Google Pixel 4a - Unlocked Android Smartphone - 128 GB of Storage - Up to 24 Hour Battery - Barely Blue',
            'image': 'https://m.media-amazon.com/images/I/61NrGFKn2LS._AC_UY218_.jpg',
            'full_link': 'https://www.amazon.com/dp/B095PY85HG/?psc=1',
            'prices': {
                'current_price': 349.0,
                'previous_price': -1.0,
                'currency': '$'
            },
            'reviews': {
                'total_reviews': 9221,
                'stars': 4.6
            }, 'prime': False,
            'sponsored': False
        },
        {
            'asin': 'B08H8VZ6PV',
            'title': 'Google Pixel 4a with 5G - Android Phone - New Unlocked Smartphone with Night Sight and Ultrawide Lens - Just Black',
            'image': 'https://m.media-amazon.com/images/I/71C0OH4WfpL._AC_UY218_.jpg',
            'full_link': 'https://www.amazon.com/dp/B08H8VZ6PV/?psc=1',
            'prices': {
                'current_price': 474.89,
                'previous_price': 499.0,
                'currency': '$'
            },
            'reviews': {
                'total_reviews': 2288,
                'stars': 4.6
            },
            'prime': False,
            'sponsored': False
        },
        {
            'asin': 'B07YMNLXL3',
            'title': 'Google Pixel 4 - Just Black - 64GB - Unlocked',
            'image': 'https://m.media-amazon.com/images/I/713N4SwTtKL._AC_UY218_.jpg',
            'full_link': 'https://www.amazon.com/dp/B07YMNLXL3/?psc=1',
            'prices': {
                'current_price': 377.58,
                'previous_price': -1.0,
                'currency': '$'
            },
            'reviews': {
                'total_reviews': 877,
                'stars': 4.4
            },
            'prime': False,
            'sponsored': False
        },
        {
            'asin': 'B0824CTTQ7',
            'title': 'Pixel 4 - Clearly White - 64GB - Unlocked (Renewed)',
            'image': 'https://m.media-amazon.com/images/I/61D4hZNZ5jL._AC_UY218_.jpg',
            'full_link': 'https://www.amazon.com/dp/B0824CTTQ7/?psc=1',
            'prices': {
                'current_price': 241.0,
                'previous_price': 418.0,
                'currency': '$'
            },
            'reviews': {
                'total_reviews': 452,
                'stars': 4.3
            }, 'prime': False,
            'sponsored': False
        },
        {
            'asin': 'B0175FR85W', 'title': 'Pixels',
            'image': 'https://m.media-amazon.com/images/I/91xrsmHJ9cL._AC_UY218_.jpg',
            'full_link': 'https://www.amazon.com/dp/B0175FR85W/?psc=1',
            'prices': {
                'current_price': 2.99,
                'previous_price': -1.0,
                'currency': '$'
            },
            'reviews': {
                'total_reviews': 15791,
                'stars': 4.6
            },
            'prime': False,
            'sponsored': False
        },
        {
            'asin': 'B0766HPGYP',
            'title': 'Google Pixel 2 128GB Unlocked GSM/CDMA 4G LTE Octa-Core Phone w/ 12.2MP Camera - Just Black',
            'image': 'https://m.media-amazon.com/images/I/61v0enHOXpL._AC_UY218_.jpg',
            'full_link': 'https://www.amazon.com/dp/B0766HPGYP/?psc=1',
            'prices': {
                'current_price': 130.99,
                'previous_price': -1.0,
                'currency': '$'
            },
            'reviews': {
                'total_reviews': 446,
                'stars': 4.0
            },
            'prime': False,
            'sponsored': False
        },
        {
            'asin': 'B07KSSQQLZ',
            'title': 'Google - Pixel 3 with 64GB Memory Cell Phone (Unlocked) - Not Pink',
            'image': 'https://m.media-amazon.com/images/I/71krmniFaeL._AC_UY218_.jpg',
            'full_link': 'https://www.amazon.com/dp/B07KSSQQLZ/?psc=1',
            'prices': {
                'current_price': 219.95, 'previous_price': -1.0,
                'currency': '$'
            },
            'reviews': {
                'total_reviews': 617,
                'stars': 4.3
            },
            'prime': False,
            'sponsored': False
        },
        {
            'asin': 'B07R7DY911',
            'title': 'Google - Pixel 3a with 64GB Memory Cell Phone (Unlocked) - Just Black',
            'image': 'https://m.media-amazon.com/images/I/81T-FKC695L._AC_UY218_.jpg',
            'full_link': 'https://www.amazon.com/dp/B07R7DY911/?psc=1',
            'prices': {
                'current_price': 279.99,
                'previous_price': 399.0,
                'currency': '$'
            },
            'reviews': {
                'total_reviews': 8374,
                'stars': 4.4
            },
            'prime': False,
            'sponsored': False
        },
        {
            'asin': 'B095H15WLP',
            'title': 'USB C Fast Charger, Wangmai 30W A&C Dual-Port Foldable PD Type c Charger, USB C Wall Charger Block for iPhone 13/12/11/Pro Max/XS/XR/X,iPad Pro, Pixel, Galaxy, and More',
            'image': 'https://m.media-amazon.com/images/I/41d2GIVkmaL._AC_UY218_.jpg',
            'full_link': 'https://www.amazon.com/dp/B095H15WLP/?psc=1',
            'prices': {
                'current_price': 13.99,
                'previous_price': 23.99,
                'currency': '$'
            },
            'reviews': {
                'total_reviews': 29,
                'stars': 4.9
            },
            'prime': False,
            'sponsored': True
        },
        {
            'asin': 'B098V2B362',
            'title': 'Google Pixel 3 Unlocked Smartphone - 64GB Memory Cell Phone, Just Black, w/Charging Stand, Wired Earbuds and Google Charger - Bundle Set',
            'image': 'https://m.media-amazon.com/images/I/61YNb0vcezS._AC_UY218_.jpg',
            'full_link': 'https://www.amazon.com/dp/B098V2B362/?psc=1',
            'prices': {
                'current_price': 225.0,
                'previous_price': -1.0,
                'currency': '$'
            },
            'reviews': {
                'total_reviews': 37,
                'stars': 4.0
            }, 'prime': False,
            'sponsored': False
        },
        {
            'asin': 'B09DV93S9K',
            'title': 'Google Pixel 5A 5G 128GB 6GB RAM Factory Unlocked (GSM Only | No CDMA - not Compatible with Verizon/Sprint) International Version - Black',
            'image': 'https://m.media-amazon.com/images/I/51E7J1JKKXL._AC_UY218_.jpg',
            'full_link': 'https://www.amazon.com/dp/B09DV93S9K/?psc=1',
            'prices': {
                'current_price': 472.83,
                'previous_price': 515.0,
                'currency': '$'
            },
            'reviews': {
                'total_reviews': 49,
                'stars': 4.2
            },
            'prime': False,
            'sponsored': False
        },
        {
            'asin': 'B0766TPHSH',
            'title': 'Google Pixel 2 XL 64GB Unlocked GSM/CDMA 4G LTE Octa-Core Smart Phone (Just Black)',
            'image': 'https://m.media-amazon.com/images/I/81dXcgzgqkL._AC_UY218_.jpg',
            'full_link': 'https://www.amazon.com/dp/B0766TPHSH/?psc=1',
            'prices': {
                'current_price': 154.99,
                'previous_price': -1.0,
                'currency': '$'
            },
            'reviews': {
                'total_reviews': 216,
                'stars': 4.4
            }, 'prime': False,
            'sponsored': False
        },
        {
            'asin': 'B01EGAMEC6', 'title': 'Pixels (4K UHD)',
            'image': 'https://m.media-amazon.com/images/I/914FRjkuyHL._AC_UY218_.jpg',
            'full_link': 'https://www.amazon.com/dp/B01EGAMEC6/?psc=1',
            'prices': {
                'current_price': 3.99,
                'previous_price': -1.0,
                'currency': '$'
            },
            'reviews': {
                'total_reviews': 2272,
                'stars': 4.7
            },
            'prime': False,
            'sponsored': False
        },
        {
            'asin': 'B08KS4FKVP',
            'title': 'Pixel C100 LED Continuous Output Video Light with Barn Door/4 Color Filters, 120W 5600K 98000lux CRI97+ TLCI99+ Photography Studio Light, Remote Controller for Portrait Shooting and Video Recording',
            'image': 'https://m.media-amazon.com/images/I/71pBI4nky-L._AC_UY218_.jpg',
            'full_link': 'https://www.amazon.com/dp/B08KS4FKVP/?psc=1',
            'prices': {
                'current_price': 169.99,
                'previous_price': 269.99,
                'currency': '$'
            },
            'reviews': {
                'total_reviews': 10,
                'stars': 4.4
            },
            'prime': False,
            'sponsored': True
        },
        {
            'asin': 'B08R61G69Q',
            'title': 'Google Pixel 4a with 5G - Android Phone - New Unlocked Smartphone with Night Sight and Ultrawide Lens - Just Black (Renewed)',
            'image': 'https://m.media-amazon.com/images/I/71DgN0WGe4L._AC_UY218_.jpg',
            'full_link': 'https://www.amazon.com/dp/B08R61G69Q/?psc=1',
            'prices': {
                'current_price': 358.0,
                'previous_price': 474.89,
                'currency': '$'
            },
            'reviews': {
                'total_reviews': 123,
                'stars': 4.2
            },
            'prime': False,
            'sponsored': False
        },
        {
            'asin': 'B082YF9MMW',
            'title': 'Unlocked Google Pixel 4 - 64GB - Just Black - GA01187-US (Renewed)',
            'image': 'https://m.media-amazon.com/images/I/51Bch2bRtLL._AC_UY218_.jpg',
            'full_link': 'https://www.amazon.com/dp/B082YF9MMW/?psc=1',
            'prices': {
                'current_price': 244.99,
                'previous_price': 377.58,
                'currency': '$'
            },
            'reviews': {
                'total_reviews': 345,
                'stars': 4.4
            },
            'prime': False,
            'sponsored': False
        },
        {
            'asin': 'B08MV7HWFK',
            'title': 'Unlocked Google Pixel 5 128GB Just Black GA01316-US (Renewed)',
            'image': 'https://m.media-amazon.com/images/I/81Uho2XBxQL._AC_UY218_.jpg',
            'full_link': 'https://www.amazon.com/dp/B08MV7HWFK/?psc=1',
            'prices': {
                'current_price': 429.0,
                'previous_price': 960.0,
                'currency': '$'
            },
            'reviews': {
                'total_reviews': 190,
                'stars': 4.0
            },
            'prime': False,
            'sponsored': False
        },
        {
            'asin': 'B07KX8DXW8',
            'title': 'Google Pixel 3 64GB Unlocked GSM & CDMA 4G LTE - Just Black (Renewed)',
            'image': 'https://m.media-amazon.com/images/I/51YNSBaJ6oL._AC_UY218_.jpg',
            'full_link': 'https://www.amazon.com/dp/B07KX8DXW8/?psc=1',
            'prices': {
                'current_price': 150.99,
                'previous_price': -1.0,
                'currency': '$'
            },
            'reviews': {
                'total_reviews': 248,
                'stars': 4.0
            },
            'prime': False,
            'sponsored': False
        },
        {
            'asin': 'B09BQWHTQK',
            'title': 'Syncwire USB C Charger 30W Fast Wall Charger GaN II Mini Power Adapter PD Charger for iPhone 13 Pro Max/iPhone 12 Pro Max, MacBook Air, iPad Pro,Galaxy S21/ S21+,Pixel 6 Pro/6(Cable not Included)',
            'image': 'https://m.media-amazon.com/images/I/41dJiKfatVL._AC_UY218_.jpg',
            'full_link': 'https://www.amazon.com/dp/B09BQWHTQK/?psc=1',
            'prices': {
                'current_price': 16.99,
                'previous_price': -1.0,
                'currency': '$'
            },
            'reviews': {
                'total_reviews': 181,
                'stars': 4.6
            },
            'prime': False,
            'sponsored': True
        },
        {
            'asin': 'B09KMQK8QY',
            'title': 'Jusy Case for Google Pixel 6 Pro, Enhanced Grip Durable Light Shockproof Flexible TPU Rubber Protective Cover for Pixel 6 Pro (Red)',
            'image': 'https://m.media-amazon.com/images/I/71CnNIF3FSL._AC_UY218_.jpg',
            'full_link': 'https://www.amazon.com/dp/B09KMQK8QY/?psc=1',
            'prices': {
                'current_price': 8.99,
                'previous_price': -1.0,
                'currency': '$'
            },
            'reviews': {
                'total_reviews': 5,
                'stars': 4.1
            },
            'prime': False,
            'sponsored': True
        }
    ]
}

zlatan: Dict = {'error': False, 'current_page': 1, 'next_page': 2,
                'results': [{'asin': '081298692X',
                             'title': 'I Am Zlatan: My Story On and Off the Field',
                             'image': 'https://m.media-amazon.com/images/I/91ivijEtDsL._AC_UY218_.jpg',
                             'full_link': 'https://www.amazon.com/dp/081298692X/?psc=1',
                             'prices': {'current_price': 9.99,
                                        'previous_price': 18.0,
                                        'currency': '$'},
                             'reviews': {'total_reviews': 351, 'stars': 4.7},
                             'prime': False, 'sponsored': False},
                            {'asin': '024129715X',
                             'title': 'I Am Football: Zlatan Ibrahimovic',
                             'image': 'https://m.media-amazon.com/images/I/81mKFY0pTtL._AC_UY218_.jpg',
                             'full_link': 'https://www.amazon.com/dp/024129715X/?psc=1',
                             'prices': {'current_price': 39.0,
                                        'previous_price': 47.95,
                                        'currency': '$'},
                             'reviews': {'total_reviews': 220, 'stars': 4.7},
                             'prime': False, 'sponsored': False},
                            {'asin': 'B01N1FE2XM',
                             'title': 'I Am Zlatan Ibrahimovic',
                             'image': 'https://m.media-amazon.com/images/I/81-NkdgT2nL._AC_UY218_.jpg',
                             'full_link': 'https://www.amazon.com/dp/B01N1FE2XM/?psc=1',
                             'prices': {'current_price': 0.0,
                                        'previous_price': 23.44,
                                        'currency': '$'},
                             'reviews': {'total_reviews': 981, 'stars': 4.5},
                             'prime': False, 'sponsored': False},
                            {'asin': '1545175640',
                             'title': 'Zlatan Style: The funniest Zlatan Ibrahimovic quotes!',
                             'image': 'https://m.media-amazon.com/images/I/71EaTQVtjQL._AC_UY218_.jpg',
                             'full_link': 'https://www.amazon.com/dp/1545175640/?psc=1',
                             'prices': {'current_price': 0.0,
                                        'previous_price': -1.0,
                                        'currency': '$'},
                             'reviews': {'total_reviews': 14, 'stars': 4.8},
                             'prime': False, 'sponsored': False},
                            {'asin': 'B018L0UPG4',
                             'title': 'Zlatan Ibrahimović Poster - Sweden Soccer Art',
                             'image': 'https://m.media-amazon.com/images/I/810-tTBldWL._AC_UY218_.jpg',
                             'full_link': 'https://www.amazon.com/dp/B018L0UPG4/?psc=1',
                             'prices': {'current_price': 11.48,
                                        'previous_price': -1.0,
                                        'currency': '$'},
                             'reviews': {'total_reviews': 4, 'stars': 5.0},
                             'prime': False, 'sponsored': False},
                            {'asin': '0008263507',
                             'title': 'The Little Book of Zlatan',
                             'image': 'https://m.media-amazon.com/images/I/51QxneI6X3L._AC_UY218_.jpg',
                             'full_link': 'https://www.amazon.com/dp/0008263507/?psc=1',
                             'prices': {'current_price': 9.99,
                                        'previous_price': -1.0,
                                        'currency': '$'},
                             'reviews': {'total_reviews': 5, 'stars': 3.5},
                             'prime': False, 'sponsored': False},
                            {'asin': 'B01GQ26JGY',
                             'title': 'Becoming Zlatan [DVD]',
                             'image': 'https://m.media-amazon.com/images/I/91rI86N6dHL._AC_UY218_.jpg',
                             'full_link': 'https://www.amazon.com/dp/B01GQ26JGY/?psc=1',
                             'prices': {'current_price': 24.22,
                                        'previous_price': -1.0,
                                        'currency': '$'},
                             'reviews': {'total_reviews': 97, 'stars': 4.4},
                             'prime': False, 'sponsored': False},
                            {'asin': 'B013J5QT6Q',
                             'title': 'Soy Zlatan Ibrahimović: Mi historia contada a David Lagercrantz (Deportes (corner)) (Spanish Edition)',
                             'image': 'https://m.media-amazon.com/images/I/91aReGnXrTL._AC_UY218_.jpg',
                             'full_link': 'https://www.amazon.com/dp/B013J5QT6Q/?psc=1',
                             'prices': {'current_price': 0.0,
                                        'previous_price': 9.03,
                                        'currency': '$'},
                             'reviews': {'total_reviews': 139, 'stars': 4.7},
                             'prime': False, 'sponsored': False},
                            {'asin': '0789211696',
                             'title': 'Zlatan (World Soccer Legends)',
                             'image': 'https://m.media-amazon.com/images/I/41Rcym1+dCL._AC_UY218_.jpg',
                             'full_link': 'https://www.amazon.com/dp/0789211696/?psc=1',
                             'prices': {'current_price': 12.95,
                                        'previous_price': -1.0,
                                        'currency': '$'},
                             'reviews': {'total_reviews': 4, 'stars': 5.0},
                             'prime': False, 'sponsored': False},
                            {'asin': '1786068109',
                             'title': 'Zlatan: From the Playground to the Pitch (Ultimate Football Heroes)',
                             'image': 'https://m.media-amazon.com/images/I/71tzkUg35LL._AC_UY218_.jpg',
                             'full_link': 'https://www.amazon.com/dp/1786068109/?psc=1',
                             'prices': {'current_price': 6.99,
                                        'previous_price': 7.99,
                                        'currency': '$'},
                             'reviews': {'total_reviews': 113, 'stars': 4.7},
                             'prime': False, 'sponsored': False},
                            {'asin': '1533015643',
                             'title': 'Zlatan and the Spring Fairy',
                             'image': 'https://m.media-amazon.com/images/I/41Qy+jnjABL._AC_UY218_.jpg',
                             'full_link': 'https://www.amazon.com/dp/1533015643/?psc=1',
                             'prices': {'current_price': 6.23,
                                        'previous_price': 10.8,
                                        'currency': '$'},
                             'reviews': {'total_reviews': 0, 'stars': -1.0},
                             'prime': False, 'sponsored': False},
                            {'asin': '3492306446',
                             'title': 'Ich bin Zlatan: Meine Geschichte',
                             'image': 'https://m.media-amazon.com/images/I/71JYCjVwmrL._AC_UY218_.jpg',
                             'full_link': 'https://www.amazon.com/dp/3492306446/?psc=1',
                             'prices': {'current_price': 0.0,
                                        'previous_price': 12.49,
                                        'currency': '$'},
                             'reviews': {'total_reviews': 605, 'stars': 4.6},
                             'prime': False, 'sponsored': False}]}

alphago: Dict = {'error': False, 'current_page': 1, 'next_page': 2,
                 'results': [{'asin': '1542800714',
                              'title': 'AlphaGo vs Lee Sedol: The Match that Changed the World of Go',
                              'image': 'https://m.media-amazon.com/images/I/71uaaQ6KwbL._AC_UY218_.jpg',
                              'full_link': 'https://www.amazon.com/dp/1542800714/?psc=1',
                              'prices': {'current_price': 15.85,
                                         'previous_price': -1.0,
                                         'currency': '$'},
                              'reviews': {'total_reviews': 9, 'stars': 4.1},
                              'prime': False, 'sponsored': False},
                             {'asin': '0648662578',
                              'title': 'AlphaGo Opening Research: From Joseki to the Middle Game',
                              'image': 'https://m.media-amazon.com/images/I/41Ad1GoJ+5L._AC_UY218_.jpg',
                              'full_link': 'https://www.amazon.com/dp/0648662578/?psc=1',
                              'prices': {'current_price': 9.99,
                                         'previous_price': 27.99,
                                         'currency': '$'},
                              'reviews': {'total_reviews': 2, 'stars': 5.0},
                              'prime': False, 'sponsored': False},
                             {'asin': 'B08HCJY7R7',
                              'title': 'JIAXIN Ornaments Room Decor Alphago Bottle Countertop Wine Holder for Table Top Modern Anubis Art Statue Design Wine Bottle Storage Rack Perfect Wine Holder,M',
                              'image': 'https://m.media-amazon.com/images/I/51WkFddoN-L._AC_UY218_.jpg',
                              'full_link': 'https://www.amazon.com/dp/B08HCJY7R7/?psc=1',
                              'prices': {'current_price': 38.56,
                                         'previous_price': -1.0,
                                         'currency': '$'},
                              'reviews': {'total_reviews': 0, 'stars': -1.0},
                              'prime': False, 'sponsored': False},
                             {'asin': 'B076PJ8SB2',
                              'title': 'AlphaGo Zero AI vs AI 20 games AlphaGo Zero vs AlphaGo Master IGOKAIKATSU SERIES (Japanese Edition)',
                              'image': 'https://m.media-amazon.com/images/I/81wx9Tc171L._AC_UY218_.jpg',
                              'full_link': 'https://www.amazon.com/dp/B076PJ8SB2/?psc=1',
                              'prices': {'current_price': 0.0,
                                         'previous_price': -1.0,
                                         'currency': '$'},
                              'reviews': {'total_reviews': 2, 'stars': 4.5},
                              'prime': False, 'sponsored': False},
                             {'asin': '1731135297',
                              'title': "Playing AlphaGo's Early 3-3 Invasion",
                              'image': 'https://m.media-amazon.com/images/I/514NyM-+TiL._AC_UY218_.jpg',
                              'full_link': 'https://www.amazon.com/dp/1731135297/?psc=1',
                              'prices': {'current_price': 12.85,
                                         'previous_price': -1.0,
                                         'currency': '$'},
                              'reviews': {'total_reviews': 3, 'stars': 4.7},
                              'prime': False, 'sponsored': False},
                             {'asin': '1974674584',
                              'title': 'AlphaGo vs. Ke Jie 9P',
                              'image': 'https://m.media-amazon.com/images/I/41RE0gaMYJL._AC_UY218_.jpg',
                              'full_link': 'https://www.amazon.com/dp/1974674584/?psc=1',
                              'prices': {'current_price': 17.85,
                                         'previous_price': -1.0,
                                         'currency': '$'},
                              'reviews': {'total_reviews': 7, 'stars': 4.4},
                              'prime': False, 'sponsored': False},
                             {'asin': '1981642005',
                              'title': "Rethinking Opening Strategy: AlphaGo's Impact on Pro Play",
                              'image': 'https://m.media-amazon.com/images/I/612jTbYFd7L._AC_UY218_.jpg',
                              'full_link': 'https://www.amazon.com/dp/1981642005/?psc=1',
                              'prices': {'current_price': 16.85,
                                         'previous_price': -1.0,
                                         'currency': '$'},
                              'reviews': {'total_reviews': 6, 'stars': 4.5},
                              'prime': False, 'sponsored': False},
                             {'asin': '1090423365',
                              'title': "Using AlphaGo's Enlarged Corner Enclosures",
                              'image': 'https://m.media-amazon.com/images/I/51r6bri4fZL._AC_UY218_.jpg',
                              'full_link': 'https://www.amazon.com/dp/1090423365/?psc=1',
                              'prices': {'current_price': 17.95,
                                         'previous_price': -1.0,
                                         'currency': '$'},
                              'reviews': {'total_reviews': 3, 'stars': 5.0},
                              'prime': False, 'sponsored': False},
                             {'asin': '1954289367',
                              'title': 'Go for Beginners: A Step-By-Step Guide to Learning the Game of Go',
                              'image': 'https://m.media-amazon.com/images/I/51GB0XuHw2L._AC_UY218_.jpg',
                              'full_link': 'https://www.amazon.com/dp/1954289367/?psc=1',
                              'prices': {'current_price': 10.72,
                                         'previous_price': 12.65,
                                         'currency': '$'},
                              'reviews': {'total_reviews': 128, 'stars': 4.4},
                              'prime': False, 'sponsored': True},
                             {'asin': '1723535265',
                              'title': "Playing AlphaGo's Early 3-3 Point Invasion",
                              'image': 'https://m.media-amazon.com/images/I/51tqcMyHCvL._AC_UY218_.jpg',
                              'full_link': 'https://www.amazon.com/dp/1723535265/?psc=1',
                              'prices': {'current_price': 16.75,
                                         'previous_price': -1.0,
                                         'currency': '$'},
                              'reviews': {'total_reviews': 0, 'stars': -1.0},
                              'prime': False, 'sponsored': False},
                             {'asin': 'B07Q42BV91',
                              'title': 'Deep Learning with Keras from Scratch: Grasp deep Learning/keras from scratch like AlphaGo Zero within 40 days',
                              'image': 'https://m.media-amazon.com/images/I/81frWIIXVXL._AC_UY218_.jpg',
                              'full_link': 'https://www.amazon.com/dp/B07Q42BV91/?psc=1',
                              'prices': {'current_price': 39.99,
                                         'previous_price': 39.99,
                                         'currency': '$'},
                              'reviews': {'total_reviews': 4, 'stars': 3.8},
                              'prime': False, 'sponsored': False},
                             {'asin': 'B008J0DQJ0', 'title': 'Sunshine Hotel',
                              'image': 'https://m.media-amazon.com/images/I/81Hu7N4-RRL._AC_UY218_.jpg',
                              'full_link': 'https://www.amazon.com/dp/B008J0DQJ0/?psc=1',
                              'prices': {'current_price': 2.99,
                                         'previous_price': -1.0,
                                         'currency': '$'},
                              'reviews': {'total_reviews': 258, 'stars': 4.4},
                              'prime': False, 'sponsored': False},
                             {'asin': 'B074743PQN',
                              'title': 'Reasons To Believe',
                              'image': 'https://m.media-amazon.com/images/I/81p6YdCxRwL._AC_UY218_.jpg',
                              'full_link': 'https://www.amazon.com/dp/B074743PQN/?psc=1',
                              'prices': {'current_price': 1.99,
                                         'previous_price': -1.0,
                                         'currency': '$'},
                              'reviews': {'total_reviews': 73, 'stars': 3.3},
                              'prime': False, 'sponsored': False},
                             {'asin': 'B0008EJXEW',
                              'title': 'WE Games Wood GO Set with Pull Out Drawers -12 in.',
                              'image': 'https://m.media-amazon.com/images/I/71yzv3fB5PL._AC_UY218_.jpg',
                              'full_link': 'https://www.amazon.com/dp/B0008EJXEW/?psc=1',
                              'prices': {'current_price': 43.99,
                                         'previous_price': 59.99,
                                         'currency': '$'},
                              'reviews': {'total_reviews': 676, 'stars': 4.3},
                              'prime': False, 'sponsored': False},
                             {'asin': 'B00OD4ZGB2',
                              'title': 'Brybelly Go Set with Reversible Bamboo Go Board | Measures 19x19 & 13x13 and Includes Bowls & Bakelite Stones | 2-Player - Classic Chinese Strategy Board Game',
                              'image': 'https://m.media-amazon.com/images/I/61CDTYgw+cL._AC_UY218_.jpg',
                              'full_link': 'https://www.amazon.com/dp/B00OD4ZGB2/?psc=1',
                              'prices': {'current_price': 64.99,
                                         'previous_price': 74.99,
                                         'currency': '$'},
                              'reviews': {'total_reviews': 699, 'stars': 4.6},
                              'prime': False, 'sponsored': False},
                             {'asin': 'B08MWRKDYV',
                              'title': 'AMEROUS Go Set with Etched Reversible 19x19 / 13x13 Bamboo Board - Single Convex Stones - Bowls, Go Game Set Education for Beginner Kids Adults, Classic Chinese Strategy Board Game ( WEIQI )',
                              'image': 'https://m.media-amazon.com/images/I/71lyX5kJXTL._AC_UY218_.jpg',
                              'full_link': 'https://www.amazon.com/dp/B08MWRKDYV/?psc=1',
                              'prices': {'current_price': 79.99,
                                         'previous_price': -1.0,
                                         'currency': '$'},
                              'reviews': {'total_reviews': 57, 'stars': 4.8},
                              'prime': False, 'sponsored': False}]}

macbook: Dict = {'error': False, 'current_page': 1, 'next_page': 2,
                 'results': [{'asin': 'B09JQK9DK5',
                              'title': '2021 Apple MacBook Pro (16-inch, Apple M1 Pro chip with 10‑core CPU and 16‑core GPU, 16GB RAM, 1TB SSD) - Space Gray',
                              'image': 'https://m.media-amazon.com/images/I/61aUBxqc5PL._AC_UY218_.jpg',
                              'full_link': 'https://www.amazon.com/dp/B09JQK9DK5/?psc=1',
                              'prices': {'current_price': 2699.0,
                                         'previous_price': -1.0,
                                         'currency': '$'},
                              'reviews': {'total_reviews': 65, 'stars': 4.4},
                              'prime': False, 'sponsored': True},
                             {'asin': 'B0776YMQLM',
                              'title': 'Apple Leather Sleeve (for 12-inch MacBook) - Saddle Brown',
                              'image': 'https://m.media-amazon.com/images/I/810bXOoCW+L._AC_UY218_.jpg',
                              'full_link': 'https://www.amazon.com/dp/B0776YMQLM/?psc=1',
                              'prices': {'current_price': 104.83,
                                         'previous_price': 149.0,
                                         'currency': '$'},
                              'reviews': {'total_reviews': 68, 'stars': 4.5},
                              'prime': False, 'sponsored': True},
                             {'asin': 'B09JQML3NL',
                              'title': '2021 Apple MacBook Pro (16-inch, Apple M1 Pro chip with 10‑core CPU and 16‑core GPU, 16GB RAM, 1TB SSD) - Silver',
                              'image': 'https://m.media-amazon.com/images/I/61Y30DpqRVL._AC_UY218_.jpg',
                              'full_link': 'https://www.amazon.com/dp/B09JQML3NL/?psc=1',
                              'prices': {'current_price': 2699.0,
                                         'previous_price': -1.0,
                                         'currency': '$'},
                              'reviews': {'total_reviews': 65, 'stars': 4.4},
                              'prime': False, 'sponsored': False},
                             {'asin': 'B09JQL8KP9',
                              'title': '2021 Apple MacBook Pro (14-inch, Apple M1 Pro chip with 8‑core CPU and 14‑core GPU, 16GB RAM, 512GB SSD) - Silver',
                              'image': 'https://m.media-amazon.com/images/I/61cCf94xIEL._AC_UY218_.jpg',
                              'full_link': 'https://www.amazon.com/dp/B09JQL8KP9/?psc=1',
                              'prices': {'current_price': 1999.0,
                                         'previous_price': -1.0,
                                         'currency': '$'},
                              'reviews': {'total_reviews': 74, 'stars': 4.7},
                              'prime': False, 'sponsored': False},
                             {'asin': 'B077QWM132',
                              'title': '(Renewed) Apple MacBook Pro 13in Core i5 Retina 2.7GHz (MF840LL/A), 8GB Memory, 256GB Solid State Drive',
                              'image': 'https://m.media-amazon.com/images/I/718L2WEaryL._AC_UY218_.jpg',
                              'full_link': 'https://www.amazon.com/dp/B077QWM132/?psc=1',
                              'prices': {'current_price': 539.0,
                                         'previous_price': -1.0,
                                         'currency': '$'},
                              'reviews': {'total_reviews': 1040, 'stars': 4.3},
                              'prime': False, 'sponsored': False},
                             {'asin': 'B078GX9R5W',
                              'title': 'Apple 13in MacBook Pro, Retina Display, 2.3GHz Intel Core i5 Dual Core, 8GB RAM, 128GB SSD, Space Grey, MPXQ2LL/A (Renewed)',
                              'image': 'https://m.media-amazon.com/images/I/71nM55mRvxL._AC_UY218_.jpg',
                              'full_link': 'https://www.amazon.com/dp/B078GX9R5W/?psc=1',
                              'prices': {'current_price': 645.99,
                                         'previous_price': -1.0,
                                         'currency': '$'},
                              'reviews': {'total_reviews': 1155, 'stars': 4.1},
                              'prime': False, 'sponsored': False},
                             {'asin': 'B008ALAAV0',
                              'title': 'Apple 85W MagSafe 2 Power Adapter (for MacBook Pro with Retina Display)',
                              'image': 'https://m.media-amazon.com/images/I/41dQs8oZuWL._AC_UY218_.jpg',
                              'full_link': 'https://www.amazon.com/dp/B008ALAAV0/?psc=1',
                              'prices': {'current_price': 54.99,
                                         'previous_price': 90.0,
                                         'currency': '$'},
                              'reviews': {'total_reviews': 8252, 'stars': 4.8},
                              'prime': False, 'sponsored': True},
                             {'asin': 'B082J572X8',
                              'title': 'Apple 13.3" MacBook Pro with Touch Bar, Intel Core i5 Quad-Core, 8GB RAM, 128GB SSD - Mid 2019, Space Gray, MUHN2LL/A (Renewed)',
                              'image': 'https://m.media-amazon.com/images/I/71i49M4hv2L._AC_UY218_.jpg',
                              'full_link': 'https://www.amazon.com/dp/B082J572X8/?psc=1',
                              'prices': {'current_price': 869.0,
                                         'previous_price': -1.0,
                                         'currency': '$'},
                              'reviews': {'total_reviews': 748, 'stars': 4.6},
                              'prime': False, 'sponsored': False},
                             {'asin': 'B01433Q792',
                              'title': '(Renewed) Apple MacBook Pro MF839LL/A 128GB Flash Storage - 8GB LPDDR3 - 13.3in with Intel Core i5 2.7 GHz',
                              'image': 'https://m.media-amazon.com/images/I/81bTK8-ei4L._AC_UY218_.jpg',
                              'full_link': 'https://www.amazon.com/dp/B01433Q792/?psc=1',
                              'prices': {'current_price': 474.99,
                                         'previous_price': -1.0,
                                         'currency': '$'},
                              'reviews': {'total_reviews': 535, 'stars': 4.3},
                              'prime': False, 'sponsored': False},
                             {'asin': 'B07ZFZ33SK',
                              'title': 'Apple Macbook Pro MJLQ2LL/A 15-inch Laptop, Intel Core i7 Processor, 16GB RAM, 256GB SSD, Mac OS X (Renewed)',
                              'image': 'https://m.media-amazon.com/images/I/81VbWDN53oL._AC_UY218_.jpg',
                              'full_link': 'https://www.amazon.com/dp/B07ZFZ33SK/?psc=1',
                              'prices': {'current_price': 739.95,
                                         'previous_price': -1.0,
                                         'currency': '$'},
                              'reviews': {'total_reviews': 392, 'stars': 4.3},
                              'prime': False, 'sponsored': False},
                             {'asin': 'B077TH4YMF',
                              'title': 'Apple MacBook Pro MLH12LL/A 13-inch Laptop with Touch Bar, 2.9GHz dual-core Intel Core i5, 8GB Memory, 256GB, Retina Display, Space Gray (Renewed)',
                              'image': 'https://m.media-amazon.com/images/I/61728+9bGAL._AC_UY218_.jpg',
                              'full_link': 'https://www.amazon.com/dp/B077TH4YMF/?psc=1',
                              'prices': {'current_price': 679.99,
                                         'previous_price': 849.99,
                                         'currency': '$'},
                              'reviews': {'total_reviews': 335, 'stars': 4.1},
                              'prime': False, 'sponsored': False},
                             {'asin': 'B081FRXXPS',
                              'title': 'Apple Leather Sleeve (for 16-inch MacBook Pro) - Saddle Brown',
                              'image': 'https://m.media-amazon.com/images/I/81XxVfatBWL._AC_UY218_.jpg',
                              'full_link': 'https://www.amazon.com/dp/B081FRXXPS/?psc=1',
                              'prices': {'current_price': 199.0,
                                         'previous_price': -1.0,
                                         'currency': '$'},
                              'reviews': {'total_reviews': 51, 'stars': 4.1},
                              'prime': False, 'sponsored': True},
                             {'asin': 'B0795941T3',
                              'title': 'Apple MacBook Pro 13.3-Inch Laptop 2.6GHz (MGX72LL/A) Retina, 8GB Memory, 256GB Solid State Drive (Renewed)',
                              'image': 'https://m.media-amazon.com/images/I/315CQ1KmlwL._AC_UY218_.jpg',
                              'full_link': 'https://www.amazon.com/dp/B0795941T3/?psc=1',
                              'prices': {'current_price': 484.0,
                                         'previous_price': -1.0,
                                         'currency': '$'},
                              'reviews': {'total_reviews': 1434, 'stars': 4.2},
                              'prime': False, 'sponsored': False},
                             {'asin': 'B07MWJBFVM',
                              'title': 'Apple MacBook Pro 13" MD101LL/A (4GB RAM, 500GB HD, macOS 10.13) - 1 Pack (Refurbished)',
                              'image': 'https://m.media-amazon.com/images/I/71P25wQd49L._AC_UY218_.jpg',
                              'full_link': 'https://www.amazon.com/dp/B07MWJBFVM/?psc=1',
                              'prices': {'current_price': 335.58,
                                         'previous_price': -1.0,
                                         'currency': '$'},
                              'reviews': {'total_reviews': 334, 'stars': 3.8},
                              'prime': False, 'sponsored': False},
                             {'asin': 'B07FQQ8DSY',
                              'title': 'Apple 15in MacBook Pro, Retina, Touch Bar, 2.9GHz Intel Core i7 Quad Core, 16GB RAM, 512GB SSD, Space Gray, MPTT2LL/A (Renewed)',
                              'image': 'https://m.media-amazon.com/images/I/613cwcMzysL._AC_UY218_.jpg',
                              'full_link': 'https://www.amazon.com/dp/B07FQQ8DSY/?psc=1',
                              'prices': {'current_price': 1450.68,
                                         'previous_price': -1.0,
                                         'currency': '$'},
                              'reviews': {'total_reviews': 429, 'stars': 4.2},
                              'prime': False, 'sponsored': False},
                             {'asin': 'B01AO1T44W',
                              'title': 'Apple MacBook Pro MF841LL/A 13.3-Inch Laptop (Intel Core i5 512GB 8 GB DDR3 SDRAM, Mac OS X) Silver (Renewed)',
                              'image': 'https://m.media-amazon.com/images/I/71xX9l5+pgL._AC_UY218_.jpg',
                              'full_link': 'https://www.amazon.com/dp/B01AO1T44W/?psc=1',
                              'prices': {'current_price': 769.0,
                                         'previous_price': -1.0,
                                         'currency': '$'},
                              'reviews': {'total_reviews': 135, 'stars': 4.3},
                              'prime': False, 'sponsored': False},
                             {'asin': 'B009VOFRYU',
                              'title': 'Apple 60W MagSafe 2 Power Adapter (for MacBook Pro with 13-inch Retina Display)',
                              'image': 'https://m.media-amazon.com/images/I/41V3rvBaeEL._AC_UY218_.jpg',
                              'full_link': 'https://www.amazon.com/dp/B009VOFRYU/?psc=1',
                              'prices': {'current_price': 72.0,
                                         'previous_price': 79.0,
                                         'currency': '$'},
                              'reviews': {'total_reviews': 4122, 'stars': 4.8},
                              'prime': False, 'sponsored': True},
                             {'asin': 'B07DRR761F',
                              'title': 'Apple MacBook Pro MLL42LL/A 13.3-inch Laptop, 2.0GHz dual-core Intel Core i5, 8GB Ram, 256GB SSD, Retina Display, Space Gray (Discontinued by Manufacturer) (Renewed)',
                              'image': 'https://m.media-amazon.com/images/I/61SRQUe+LhL._AC_UY218_.jpg',
                              'full_link': 'https://www.amazon.com/dp/B07DRR761F/?psc=1',
                              'prices': {'current_price': 529.0,
                                         'previous_price': -1.0,
                                         'currency': '$'},
                              'reviews': {'total_reviews': 224, 'stars': 4.0},
                              'prime': False, 'sponsored': False},
                             {'asin': 'B07G29RCBD',
                              'title': '(Refurbished) Apple MacBook Pro 13.3in Retina Laptop Intel i5 Dual Core 2.6GHz 8GB 128GB SSD - MGX72LL/A',
                              'image': 'https://m.media-amazon.com/images/I/71NZpTxWzRL._AC_UY218_.jpg',
                              'full_link': 'https://www.amazon.com/dp/B07G29RCBD/?psc=1',
                              'prices': {'current_price': 459.0,
                                         'previous_price': -1.0,
                                         'currency': '$'},
                              'reviews': {'total_reviews': 306, 'stars': 4.3},
                              'prime': False, 'sponsored': False},
                             {'asin': 'B07D957L3S',
                              'title': 'Apple MacBook Pro MF839LL/A 13.3in Laptop, Intel Core i5 2.7 GHz, 8GB Ram, 128GB SSD (Renewed)',
                              'image': 'https://m.media-amazon.com/images/I/315CQ1KmlwL._AC_UY218_.jpg',
                              'full_link': 'https://www.amazon.com/dp/B07D957L3S/?psc=1',
                              'prices': {'current_price': 528.0,
                                         'previous_price': -1.0,
                                         'currency': '$'},
                              'reviews': {'total_reviews': 150, 'stars': 4.2},
                              'prime': False, 'sponsored': False},
                             {'asin': 'B079GBBKGZ',
                              'title': 'Apple MacBook Pro MF839LL/A Intel Core i5-5257U X2 2.7GHz 8GB 128GB, Silver (Renewed)',
                              'image': 'https://m.media-amazon.com/images/I/81vs5TXBrlL._AC_UY218_.jpg',
                              'full_link': 'https://www.amazon.com/dp/B079GBBKGZ/?psc=1',
                              'prices': {'current_price': 499.0,
                                         'previous_price': -1.0,
                                         'currency': '$'},
                              'reviews': {'total_reviews': 365, 'stars': 4.3},
                              'prime': False, 'sponsored': False},
                             {'asin': 'B09KNTRTZW',
                              'title': 'MacBook Pro 14 inch Privacy Screen, magnetic privacy screen Compatible with MacBook Pro 14.2 in M1 2021(A2442) Anti-Spy/HD Privacy Screen/Anti Fingerprint/Anti Blue Light/Removable/easy installation',
                              'image': 'https://m.media-amazon.com/images/I/719BoAzIF5L._AC_UY218_.jpg',
                              'full_link': 'https://www.amazon.com/dp/B09KNTRTZW/?psc=1',
                              'prices': {'current_price': 41.99,
                                         'previous_price': -1.0,
                                         'currency': '$'},
                              'reviews': {'total_reviews': 0, 'stars': -1.0},
                              'prime': False, 'sponsored': True}]}

real_simple: Dict = {'error': False, 'current_page': 1, 'next_page': 2,
                     'results': [{'asin': 'B002PXW1IE', 'title': 'Real Simple',
                                  'image': 'https://m.media-amazon.com/images/I/51nCJrh7leL._AC_UY218_.jpg',
                                  'full_link': 'https://www.amazon.com/dp/B002PXW1IE/?psc=1',
                                  'prices': {'current_price': 0.0,
                                             'previous_price': 71.88,
                                             'currency': '$'},
                                  'reviews': {'total_reviews': 15255,
                                              'stars': 4.6}, 'prime': False,
                                  'sponsored': False},
                                 {'asin': 'B07QRN3QTF', 'title': 'Real Simple',
                                  'image': 'https://m.media-amazon.com/images/I/81vpxDAXuWL._AC_UY218_.jpg',
                                  'full_link': 'https://www.amazon.com/dp/B07QRN3QTF/?psc=1',
                                  'prices': {'current_price': 7.0,
                                             'previous_price': 59.88,
                                             'currency': '$'},
                                  'reviews': {'total_reviews': 645,
                                              'stars': 4.6}, 'prime': False,
                                  'sponsored': False}, {'asin': 'B096Y7PX6C',
                                                        'title': 'Real Simple Clutter-Free Home',
                                                        'image': 'https://m.media-amazon.com/images/I/81ME7Eb45jS._AC_UY218_.jpg',
                                                        'full_link': 'https://www.amazon.com/dp/B096Y7PX6C/?psc=1',
                                                        'prices': {
                                                            'current_price': 13.99,
                                                            'previous_price': 9.99,
                                                            'currency': '$'},
                                                        'reviews': {
                                                            'total_reviews': 9,
                                                            'stars': 4.3},
                                                        'prime': False,
                                                        'sponsored': False},
                                 {'asin': 'B00I8P42US',
                                  'title': 'REAL SIMPLE Magazine',
                                  'image': 'https://m.media-amazon.com/images/I/51nCJrh7leL._AC_UY218_.jpg',
                                  'full_link': 'https://www.amazon.com/dp/B00I8P42US/?psc=1',
                                  'prices': {'current_price': 10.0,
                                             'previous_price': 71.88,
                                             'currency': '$'},
                                  'reviews': {'total_reviews': 15255,
                                              'stars': 4.6}, 'prime': False,
                                  'sponsored': False}, {'asin': 'B00VU78P5E',
                                                        'title': 'simplehuman Code V Custom Fit Drawstring Recycling Trash Bags, 16-18 Liter / 4.2-4.8 Gallon, Blue, 60 Count',
                                                        'image': 'https://m.media-amazon.com/images/I/81FDKjAjncL._AC_UY218_.jpg',
                                                        'full_link': 'https://www.amazon.com/dp/B00VU78P5E/?psc=1',
                                                        'prices': {
                                                            'current_price': 16.49,
                                                            'previous_price': -1.0,
                                                            'currency': '$'},
                                                        'reviews': {
                                                            'total_reviews': 3401,
                                                            'stars': 4.8},
                                                        'prime': False,
                                                        'sponsored': False},
                                 {'asin': 'B08SMQW51X',
                                  'title': 'Real Simple Organizing Room by Room',
                                  'image': 'https://m.media-amazon.com/images/I/81TFRVW5Q9L._AC_UY218_.jpg',
                                  'full_link': 'https://www.amazon.com/dp/B08SMQW51X/?psc=1',
                                  'prices': {'current_price': 13.99,
                                             'previous_price': 9.99,
                                             'currency': '$'},
                                  'reviews': {'total_reviews': 29,
                                              'stars': 4.4}, 'prime': False,
                                  'sponsored': False}, {'asin': 'B0178R7FFK',
                                                        'title': 'REAL SIMPLE ORGANIZE',
                                                        'image': 'https://m.media-amazon.com/images/I/51WIIayTA7L._AC_UY218_.jpg',
                                                        'full_link': 'https://www.amazon.com/dp/B0178R7FFK/?psc=1',
                                                        'prices': {
                                                            'current_price': 13.99,
                                                            'previous_price': -1.0,
                                                            'currency': '$'},
                                                        'reviews': {
                                                            'total_reviews': 0,
                                                            'stars': -1.0},
                                                        'prime': False,
                                                        'sponsored': False},
                                 {'asin': 'B091FYVBN5',
                                  'title': 'Real Simple the Power of Positivity',
                                  'image': 'https://m.media-amazon.com/images/I/81Nk1gt3XDL._AC_UY218_.jpg',
                                  'full_link': 'https://www.amazon.com/dp/B091FYVBN5/?psc=1',
                                  'prices': {'current_price': 6.86,
                                             'previous_price': 13.99,
                                             'currency': '$'},
                                  'reviews': {'total_reviews': 38,
                                              'stars': 4.5}, 'prime': False,
                                  'sponsored': False}, {'asin': '1647398657',
                                                        'title': 'Ramen Made Simple: A Step-by-Step Guide',
                                                        'image': 'https://m.media-amazon.com/images/I/81a2lwE4gXL._AC_UY218_.jpg',
                                                        'full_link': 'https://www.amazon.com/dp/1647398657/?psc=1',
                                                        'prices': {
                                                            'current_price': 10.99,
                                                            'previous_price': 13.99,
                                                            'currency': '$'},
                                                        'reviews': {
                                                            'total_reviews': 123,
                                                            'stars': 4.6},
                                                        'prime': False,
                                                        'sponsored': True},
                                 {'asin': '0848742885',
                                  'title': 'The Real Simple Guide to Real Life: Adulthood Made Easy',
                                  'image': 'https://m.media-amazon.com/images/I/615+zkxSxyL._AC_UY218_.jpg',
                                  'full_link': 'https://www.amazon.com/dp/0848742885/?psc=1',
                                  'prices': {'current_price': 9.59,
                                             'previous_price': 15.99,
                                             'currency': '$'},
                                  'reviews': {'total_reviews': 99,
                                              'stars': 4.4}, 'prime': False,
                                  'sponsored': False}, {'asin': 'B08NFKSX1Q',
                                                        'title': 'Real Simple Mental Well-Being',
                                                        'image': 'https://m.media-amazon.com/images/I/81nQx36XeuL._AC_UY218_.jpg',
                                                        'full_link': 'https://www.amazon.com/dp/B08NFKSX1Q/?psc=1',
                                                        'prices': {
                                                            'current_price': 13.99,
                                                            'previous_price': 9.99,
                                                            'currency': '$'},
                                                        'reviews': {
                                                            'total_reviews': 19,
                                                            'stars': 4.8},
                                                        'prime': False,
                                                        'sponsored': False},
                                 {'asin': 'B07CNHYHDB',
                                  'title': 'Real Simple Spring Cleaning: Refresh Your Home, Calm Your Mind',
                                  'image': 'https://m.media-amazon.com/images/I/81e5NvtZNmL._AC_UY218_.jpg',
                                  'full_link': 'https://www.amazon.com/dp/B07CNHYHDB/?psc=1',
                                  'prices': {'current_price': 13.99,
                                             'previous_price': 6.99,
                                             'currency': '$'},
                                  'reviews': {'total_reviews': 45,
                                              'stars': 4.5}, 'prime': False,
                                  'sponsored': False}, {'asin': 'B08587HT4T',
                                                        'title': 'Real Simple Secrets to a Clean Home',
                                                        'image': 'https://m.media-amazon.com/images/I/81fo-Y3sQZL._AC_UY218_.jpg',
                                                        'full_link': 'https://www.amazon.com/dp/B08587HT4T/?psc=1',
                                                        'prices': {
                                                            'current_price': 5.01,
                                                            'previous_price': 13.99,
                                                            'currency': '$'},
                                                        'reviews': {
                                                            'total_reviews': 19,
                                                            'stars': 4.4},
                                                        'prime': False,
                                                        'sponsored': False},
                                 {'asin': 'B08QST6SKK',
                                  'title': 'Commercial Real Estate: Journey Towards Financial Freedom: What Everyone Ought To Know About Commercial Real Estate Investing in 3 Simple Steps',
                                  'image': 'https://m.media-amazon.com/images/I/61e1p1U26XL._AC_UY218_.jpg',
                                  'full_link': 'https://www.amazon.com/dp/B08QST6SKK/?psc=1',
                                  'prices': {'current_price': 13.33,
                                             'previous_price': -1.0,
                                             'currency': '$'},
                                  'reviews': {'total_reviews': 68,
                                              'stars': 4.7}, 'prime': False,
                                  'sponsored': True}, {'asin': '0848756770',
                                                       'title': 'The Real Simple Method to Organizing Every Room: And How To Keep It That Way',
                                                       'image': 'https://m.media-amazon.com/images/I/61h0dJrFBbL._AC_UY218_.jpg',
                                                       'full_link': 'https://www.amazon.com/dp/0848756770/?psc=1',
                                                       'prices': {
                                                           'current_price': 10.99,
                                                           'previous_price': 12.99,
                                                           'currency': '$'},
                                                       'reviews': {
                                                           'total_reviews': 170,
                                                           'stars': 4.8},
                                                       'prime': False,
                                                       'sponsored': False},
                                 {'asin': '1603208755',
                                  'title': 'Real Simple Dinner Tonight -- Done!: 189 quick and delicious recipes',
                                  'image': 'https://m.media-amazon.com/images/I/91buXBkMQpL._AC_UY218_.jpg',
                                  'full_link': 'https://www.amazon.com/dp/1603208755/?psc=1',
                                  'prices': {'current_price': 22.59,
                                             'previous_price': 24.95,
                                             'currency': '$'},
                                  'reviews': {'total_reviews': 61,
                                              'stars': 4.6}, 'prime': False,
                                  'sponsored': False}, {'asin': '1603209239',
                                                        'title': 'Real Simple Easy, Delicious Home Cooking: 250 Recipes for Every Season and Occasion',
                                                        'image': 'https://m.media-amazon.com/images/I/5120sq2s4ZL._AC_UY218_.jpg',
                                                        'full_link': 'https://www.amazon.com/dp/1603209239/?psc=1',
                                                        'prices': {
                                                            'current_price': 31.0,
                                                            'previous_price': -1.0,
                                                            'currency': '$'},
                                                        'reviews': {
                                                            'total_reviews': 77,
                                                            'stars': 4.3},
                                                        'prime': False,
                                                        'sponsored': False},
                                 {'asin': 'B010B2L04G',
                                  'title': 'simplehuman Code H Custom Fit Drawstring Trash Bags, 30-35 Liter / 8-9 Gallon, White, 60 Count, Liners',
                                  'image': 'https://m.media-amazon.com/images/I/81AS-VwHNFL._AC_UY218_.jpg',
                                  'full_link': 'https://www.amazon.com/dp/B010B2L04G/?psc=1',
                                  'prices': {'current_price': 19.99,
                                             'previous_price': -1.0,
                                             'currency': '$'},
                                  'reviews': {'total_reviews': 8818,
                                              'stars': 4.9}, 'prime': False,
                                  'sponsored': False}, {'asin': '0998684813',
                                                        'title': 'How To Be A GREAT Salesperson...By Monday Morning!: If You Want to Increase Your Sales Read This Book. It is That Simple',
                                                        'image': 'https://m.media-amazon.com/images/I/71GHinyoLxL._AC_UY218_.jpg',
                                                        'full_link': 'https://www.amazon.com/dp/0998684813/?psc=1',
                                                        'prices': {
                                                            'current_price': 14.95,
                                                            'previous_price': -1.0,
                                                            'currency': '$'},
                                                        'reviews': {
                                                            'total_reviews': 350,
                                                            'stars': 4.4},
                                                        'prime': False,
                                                        'sponsored': True},
                                 {'asin': 'B09HCD8DF1',
                                  'title': 'Anti-Inflammatory Diet for Beginners: Simple Recipes with a Meal Plan for the Immune System',
                                  'image': 'https://m.media-amazon.com/images/I/919lGfbFANL._AC_UY218_.jpg',
                                  'full_link': 'https://www.amazon.com/dp/B09HCD8DF1/?psc=1',
                                  'prices': {'current_price': 0.0,
                                             'previous_price': -1.0,
                                             'currency': '$'},
                                  'reviews': {'total_reviews': 13,
                                              'stars': 4.9}, 'prime': False,
                                  'sponsored': True}]}
#
# for enum in range(10):
#     product: str = pixel_data['results'][enum]['title']
#
#     price: float = pixel_data['results'][enum]['prices']['current_price']
#     print(f'Product: {product} at price {price}')
